### ISSUE TITLE
Market task - A more info action on stocks

### ISSUE THREAD

**Issue by Philosophyofmany** [henrim3/wall-street#24]
We should implement an action that allows players to request more information on a stock. This information should include:

Market Capitalization: The total amount of stock in the market.
Stock Representation: The proportion of the total market that the stock represents. For example, if the market has 100,000 total shares and the Apple stock represents 6,000 shares, it constitutes 6% of the total market.
To achieve this, a player must purchase over 50% of the available stock to bring that percentage under their firm's management.

To structure the market:

Blue-Chip Stocks: These should represent 60% of the total shares in the market. Since we are offering 20 stocks, 10 of these should be blue-chip stocks. In a market with 100,000 total shares, blue-chip stocks would collectively account for 60,000 shares, with each blue-chip stock having 6,000 shares available.
Penny Stocks: These should represent the remaining 40% of the total shares. The 10 penny stocks should collectively account for 40,000 shares, with each penny stock having 4,000 shares available.
This approach ensures a balanced distribution between blue-chip and penny stocks

**Comment by iking919** [comment]
Right now using Get Stock Information for a certain stock will return the following info as an example

Name: SEI Investments Company Common Stock
Ticker: SEIC
Price: 65.65
Daily Change: 0.94%
Total Net Change: 0.94%
Current Shares Owned: 0
Market Capitalization: 6000
Stock Representation: 6.0%

Since we have 10 blue chip the market cap will essentially be 6000 for all blue chips and 4000 for all penny stocks? And then the stock representation will also be the same 6% and 4% right now? Current shares owned will display total amount of this stocks owned amongst all players. Is this correct or am I misinterpreting it? 

Also, given this, should we cap it at 6000? So once 6000 shares are owned you can't buy any more of this stock?

This will be in the stock branch.
